/*
 * TVDB API V4
 *
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * API version: 4.7.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// extended movie record
type MovieExtendedRecord struct {
	Aliases []Alias                         `json:"aliases,omitempty"`
	Artworks []ArtworkBaseRecord            `json:"artworks,omitempty"`
	AudioLanguages []string                 `json:"audioLanguages,omitempty"`
	Awards []AwardBaseRecord                `json:"awards,omitempty"`
	BoxOffice string                        `json:"boxOffice,omitempty"`
	BoxOfficeUS string `json:"boxOfficeUS,omitempty"`
	Budget string                           `json:"budget,omitempty"`
	Characters []Character                  `json:"characters,omitempty"`
	Companies *Companies                    `json:"companies,omitempty"`
	ContentRatings []ContentRating          `json:"contentRatings,omitempty"`
	FirstRelease *Release                   `json:"first_release,omitempty"`
	Genres []GenreBaseRecord                `json:"genres,omitempty"`
	Id int64                                `json:"id,omitempty"`
	Image string                            `json:"image,omitempty"`
	Inspirations []Inspiration              `json:"inspirations,omitempty"`
	LastUpdated string                      `json:"lastUpdated,omitempty"`
	Lists []ListBaseRecord                  `json:"lists,omitempty"`
	Name string                             `json:"name,omitempty"`
	NameTranslations []string `json:"nameTranslations,omitempty"`
	OriginalCountry string `json:"originalCountry,omitempty"`
	OriginalLanguage string `json:"originalLanguage,omitempty"`
	OverviewTranslations []string           `json:"overviewTranslations,omitempty"`
	ProductionCountries []ProductionCountry `json:"production_countries,omitempty"`
	Releases []Release                      `json:"releases,omitempty"`
	RemoteIds []RemoteId                    `json:"remoteIds,omitempty"`
	Runtime int32                           `json:"runtime,omitempty"`
	Score float64 `json:"score,omitempty"`
	Slug string `json:"slug,omitempty"`
	SpokenLanguages []string                `json:"spoken_languages,omitempty"`
	Status *Status                          `json:"status,omitempty"`
	Studios []StudioBaseRecord              `json:"studios,omitempty"`
	SubtitleLanguages []string              `json:"subtitleLanguages,omitempty"`
	TagOptions []TagOption                  `json:"tagOptions,omitempty"`
	Trailers []Trailer                      `json:"trailers,omitempty"`
	Translations *TranslationExtended       `json:"translations,omitempty"`
	Year string                             `json:"year,omitempty"`
}
