/*
 * TVDB API V4
 *
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * API version: 4.7.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// extended artwork record
type ArtworkExtendedRecord struct {
	EpisodeId int32 `json:"episodeId,omitempty"`
	Height int64 `json:"height,omitempty"`
	Id int64 `json:"id,omitempty"`
	Image string `json:"image,omitempty"`
	Language string `json:"language,omitempty"`
	MovieId int32 `json:"movieId,omitempty"`
	NetworkId int32 `json:"networkId,omitempty"`
	PeopleId int32 `json:"peopleId,omitempty"`
	Score float64 `json:"score,omitempty"`
	SeasonId int32 `json:"seasonId,omitempty"`
	SeriesId int32 `json:"seriesId,omitempty"`
	SeriesPeopleId int32   `json:"seriesPeopleId,omitempty"`
	Status *ArtworkStatus  `json:"status,omitempty"`
	TagOptions []TagOption `json:"tagOptions,omitempty"`
	Thumbnail string       `json:"thumbnail,omitempty"`
	ThumbnailHeight int64 `json:"thumbnailHeight,omitempty"`
	ThumbnailWidth int64 `json:"thumbnailWidth,omitempty"`
	// The artwork type corresponds to the ids from the /artwork/types endpoint.
	Type_ int64 `json:"type,omitempty"`
	UpdatedAt int64 `json:"updatedAt,omitempty"`
	Width int64 `json:"width,omitempty"`
}
