/*
 * TVDB API V4
 *
 * Documentation of [TheTVDB](https://thetvdb.com/) API V4. All related information is linked from our [Github repo](https://github.com/thetvdb/v4-api). You might also want to use our [Postman collection] (https://www.getpostman.com/collections/7a9397ce69ff246f74d0) ## Authentication 1. Use the /login endpoint and provide your API key as \"apikey\". If you have a user-supported key, also provide your subscriber PIN as \"pin\". Otherwise completely remove \"pin\" from your call. 2. Executing this call will provide you with a bearer token, which is valid for 1 month. 3. Provide your bearer token for subsequent API calls by clicking Authorize below or including in the header of all direct API calls: `Authorization: Bearer [your-token]`  ## Notes 1. \"score\" is a field across almost all entities.  We generate scores for different types of entities in various ways, so no assumptions should be made about the meaning of this value.  It is simply used to hint at relative popularity for sorting purposes. 
 *
 * API version: 4.7.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// character record
type Character struct {
	Aliases []Alias        `json:"aliases,omitempty"`
	Episode *RecordInfo    `json:"episode,omitempty"`
	EpisodeId int32        `json:"episodeId,omitempty"`
	Id int64 `json:"id,omitempty"`
	Image string `json:"image,omitempty"`
	IsFeatured bool `json:"isFeatured,omitempty"`
	MovieId int32          `json:"movieId,omitempty"`
	Movie *RecordInfo      `json:"movie,omitempty"`
	Name string            `json:"name,omitempty"`
	NameTranslations []string `json:"nameTranslations,omitempty"`
	OverviewTranslations []string `json:"overviewTranslations,omitempty"`
	PeopleId int32 `json:"peopleId,omitempty"`
	PersonImgURL string `json:"personImgURL,omitempty"`
	PeopleType string `json:"peopleType,omitempty"`
	SeriesId int32         `json:"seriesId,omitempty"`
	Series *RecordInfo     `json:"series,omitempty"`
	Sort int64             `json:"sort,omitempty"`
	TagOptions []TagOption `json:"tagOptions,omitempty"`
	Type_ int64            `json:"type,omitempty"`
	Url string `json:"url,omitempty"`
	PersonName string `json:"personName,omitempty"`
}
